package web.nl.kltn.mapper.generator;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import web.nl.kltn.model.generator.Lecturer;
import web.nl.kltn.model.generator.LecturerExample;

public interface LecturerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    long countByExample(LecturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int deleteByExample(LecturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int insert(Lecturer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int insertSelective(Lecturer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    List<Lecturer> selectByExample(LecturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    Lecturer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int updateByExampleSelective(@Param("row") Lecturer row, @Param("example") LecturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int updateByExample(@Param("row") Lecturer row, @Param("example") LecturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int updateByPrimaryKeySelective(Lecturer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int updateByPrimaryKey(Lecturer row);
}