package web.nl.kltn.mapper.generator;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import web.nl.kltn.model.generator.ProtectionRatingQuestion;
import web.nl.kltn.model.generator.ProtectionRatingQuestionExample;

public interface ProtectionRatingQuestionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table protection_rating_question
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	long countByExample(ProtectionRatingQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table protection_rating_question
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	int deleteByExample(ProtectionRatingQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table protection_rating_question
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table protection_rating_question
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	int insert(ProtectionRatingQuestion row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table protection_rating_question
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	int insertSelective(ProtectionRatingQuestion row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table protection_rating_question
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	List<ProtectionRatingQuestion> selectByExample(ProtectionRatingQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table protection_rating_question
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	ProtectionRatingQuestion selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table protection_rating_question
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	int updateByExampleSelective(@Param("row") ProtectionRatingQuestion row,
			@Param("example") ProtectionRatingQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table protection_rating_question
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	int updateByExample(@Param("row") ProtectionRatingQuestion row,
			@Param("example") ProtectionRatingQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table protection_rating_question
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	int updateByPrimaryKeySelective(ProtectionRatingQuestion row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table protection_rating_question
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	int updateByPrimaryKey(ProtectionRatingQuestion row);
}