package web.nl.kltn.mapper.generator;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import web.nl.kltn.model.generator.ReviewerQuestion;
import web.nl.kltn.model.generator.ReviewerQuestionExample;

public interface ReviewerQuestionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer_question
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	long countByExample(ReviewerQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer_question
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int deleteByExample(ReviewerQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer_question
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer_question
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int insert(ReviewerQuestion row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer_question
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int insertSelective(ReviewerQuestion row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer_question
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	List<ReviewerQuestion> selectByExample(ReviewerQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer_question
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	ReviewerQuestion selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer_question
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int updateByExampleSelective(@Param("row") ReviewerQuestion row, @Param("example") ReviewerQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer_question
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int updateByExample(@Param("row") ReviewerQuestion row, @Param("example") ReviewerQuestionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer_question
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int updateByPrimaryKeySelective(ReviewerQuestion row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer_question
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int updateByPrimaryKey(ReviewerQuestion row);
}