package web.nl.kltn.mapper.generator;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import web.nl.kltn.model.generator.ThesisUser;
import web.nl.kltn.model.generator.ThesisUserExample;

public interface ThesisUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_user
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	long countByExample(ThesisUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_user
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	int deleteByExample(ThesisUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_user
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_user
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	int insert(ThesisUser row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_user
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	int insertSelective(ThesisUser row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_user
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	List<ThesisUser> selectByExample(ThesisUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_user
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	ThesisUser selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_user
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	int updateByExampleSelective(@Param("row") ThesisUser row, @Param("example") ThesisUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_user
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	int updateByExample(@Param("row") ThesisUser row, @Param("example") ThesisUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_user
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	int updateByPrimaryKeySelective(ThesisUser row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_user
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	int updateByPrimaryKey(ThesisUser row);
}