package web.nl.kltn.mapper.generator;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import web.nl.kltn.model.generator.ThesisLecturer;
import web.nl.kltn.model.generator.ThesisLecturerExample;

public interface ThesisLecturerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    long countByExample(ThesisLecturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int deleteByExample(ThesisLecturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int insert(ThesisLecturer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int insertSelective(ThesisLecturer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    List<ThesisLecturer> selectByExample(ThesisLecturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    ThesisLecturer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int updateByExampleSelective(@Param("row") ThesisLecturer row, @Param("example") ThesisLecturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int updateByExample(@Param("row") ThesisLecturer row, @Param("example") ThesisLecturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int updateByPrimaryKeySelective(ThesisLecturer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_lecturer
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int updateByPrimaryKey(ThesisLecturer row);
}