package web.nl.kltn.mapper.generator;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import web.nl.kltn.model.generator.ThesisReviewerComment;
import web.nl.kltn.model.generator.ThesisReviewerCommentExample;

public interface ThesisReviewerCommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_reviewer_comment
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	long countByExample(ThesisReviewerCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_reviewer_comment
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int deleteByExample(ThesisReviewerCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_reviewer_comment
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_reviewer_comment
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int insert(ThesisReviewerComment row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_reviewer_comment
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int insertSelective(ThesisReviewerComment row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_reviewer_comment
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	List<ThesisReviewerComment> selectByExample(ThesisReviewerCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_reviewer_comment
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	ThesisReviewerComment selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_reviewer_comment
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int updateByExampleSelective(@Param("row") ThesisReviewerComment row,
			@Param("example") ThesisReviewerCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_reviewer_comment
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int updateByExample(@Param("row") ThesisReviewerComment row,
			@Param("example") ThesisReviewerCommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_reviewer_comment
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int updateByPrimaryKeySelective(ThesisReviewerComment row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_reviewer_comment
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int updateByPrimaryKey(ThesisReviewerComment row);
}