package web.nl.kltn.mapper.generator;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import web.nl.kltn.model.generator.ThesisReportCalendar;
import web.nl.kltn.model.generator.ThesisReportCalendarExample;

public interface ThesisReportCalendarMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_report_calendar
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	long countByExample(ThesisReportCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_report_calendar
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	int deleteByExample(ThesisReportCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_report_calendar
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_report_calendar
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	int insert(ThesisReportCalendar row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_report_calendar
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	int insertSelective(ThesisReportCalendar row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_report_calendar
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	List<ThesisReportCalendar> selectByExample(ThesisReportCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_report_calendar
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	ThesisReportCalendar selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_report_calendar
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	int updateByExampleSelective(@Param("row") ThesisReportCalendar row,
			@Param("example") ThesisReportCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_report_calendar
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	int updateByExample(@Param("row") ThesisReportCalendar row, @Param("example") ThesisReportCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_report_calendar
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	int updateByPrimaryKeySelective(ThesisReportCalendar row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_report_calendar
	 * @mbg.generated  Sun Jul 09 20:18:49 ICT 2023
	 */
	int updateByPrimaryKey(ThesisReportCalendar row);
}