package web.nl.kltn.mapper.generator;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import web.nl.kltn.model.generator.ThesisReviewCalendar;
import web.nl.kltn.model.generator.ThesisReviewCalendarExample;

public interface ThesisReviewCalendarMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_review_calendar
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	long countByExample(ThesisReviewCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_review_calendar
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int deleteByExample(ThesisReviewCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_review_calendar
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_review_calendar
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int insert(ThesisReviewCalendar row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_review_calendar
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int insertSelective(ThesisReviewCalendar row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_review_calendar
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	List<ThesisReviewCalendar> selectByExample(ThesisReviewCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_review_calendar
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	ThesisReviewCalendar selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_review_calendar
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int updateByExampleSelective(@Param("row") ThesisReviewCalendar row,
			@Param("example") ThesisReviewCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_review_calendar
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int updateByExample(@Param("row") ThesisReviewCalendar row, @Param("example") ThesisReviewCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_review_calendar
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int updateByPrimaryKeySelective(ThesisReviewCalendar row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_review_calendar
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	int updateByPrimaryKey(ThesisReviewCalendar row);
}