package web.nl.kltn.mapper.generator;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import web.nl.kltn.model.generator.ThesisDefenseCalendar;
import web.nl.kltn.model.generator.ThesisDefenseCalendarExample;

public interface ThesisDefenseCalendarMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_defense_calendar
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	long countByExample(ThesisDefenseCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_defense_calendar
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	int deleteByExample(ThesisDefenseCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_defense_calendar
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_defense_calendar
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	int insert(ThesisDefenseCalendar row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_defense_calendar
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	int insertSelective(ThesisDefenseCalendar row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_defense_calendar
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	List<ThesisDefenseCalendar> selectByExample(ThesisDefenseCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_defense_calendar
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	ThesisDefenseCalendar selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_defense_calendar
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	int updateByExampleSelective(@Param("row") ThesisDefenseCalendar row,
			@Param("example") ThesisDefenseCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_defense_calendar
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	int updateByExample(@Param("row") ThesisDefenseCalendar row,
			@Param("example") ThesisDefenseCalendarExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_defense_calendar
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	int updateByPrimaryKeySelective(ThesisDefenseCalendar row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table thesis_defense_calendar
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	int updateByPrimaryKey(ThesisDefenseCalendar row);
}