package web.nl.kltn.mapper.generator;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import web.nl.kltn.model.generator.ThesisStudent;
import web.nl.kltn.model.generator.ThesisStudentExample;

public interface ThesisStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_student
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    long countByExample(ThesisStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_student
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int deleteByExample(ThesisStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_student
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_student
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int insert(ThesisStudent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_student
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int insertSelective(ThesisStudent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_student
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    List<ThesisStudent> selectByExample(ThesisStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_student
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    ThesisStudent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_student
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int updateByExampleSelective(@Param("row") ThesisStudent row, @Param("example") ThesisStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_student
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int updateByExample(@Param("row") ThesisStudent row, @Param("example") ThesisStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_student
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int updateByPrimaryKeySelective(ThesisStudent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis_student
     *
     * @mbg.generated Sun Aug 27 18:00:43 ICT 2023
     */
    int updateByPrimaryKey(ThesisStudent row);
}