package web.nl.kltn.model.generator;

public class CriticalAssessment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.id
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.thesis_id
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private String thesisId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.marker
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private String marker;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.page_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private Integer pageNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.chapter_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private Integer chapterNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.table_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private Integer tableNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.chart_bumber
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private Integer chartBumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.drawing_board_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private Integer drawingBoardNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.image_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private Integer imageNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.document_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private Integer documentNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.calculation_software_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private Integer calculationSoftwareNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.layout
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private String layout;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.writing
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private String writing;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.technical_terms
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private String technicalTerms;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.advantage
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private String advantage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.defect
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private String defect;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.conclude
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private String conclude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.suggestion
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private Integer suggestion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.is_deleted
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private Boolean isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.created_at
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private Long createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.updated_at
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	private Long updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.id
	 * @return  the value of critical_assessment.id
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.id
	 * @param id  the value for critical_assessment.id
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.thesis_id
	 * @return  the value of critical_assessment.thesis_id
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public String getThesisId() {
		return thesisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.thesis_id
	 * @param thesisId  the value for critical_assessment.thesis_id
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setThesisId(String thesisId) {
		this.thesisId = thesisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.marker
	 * @return  the value of critical_assessment.marker
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public String getMarker() {
		return marker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.marker
	 * @param marker  the value for critical_assessment.marker
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setMarker(String marker) {
		this.marker = marker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.page_number
	 * @return  the value of critical_assessment.page_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public Integer getPageNumber() {
		return pageNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.page_number
	 * @param pageNumber  the value for critical_assessment.page_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setPageNumber(Integer pageNumber) {
		this.pageNumber = pageNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.chapter_number
	 * @return  the value of critical_assessment.chapter_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public Integer getChapterNumber() {
		return chapterNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.chapter_number
	 * @param chapterNumber  the value for critical_assessment.chapter_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setChapterNumber(Integer chapterNumber) {
		this.chapterNumber = chapterNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.table_number
	 * @return  the value of critical_assessment.table_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public Integer getTableNumber() {
		return tableNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.table_number
	 * @param tableNumber  the value for critical_assessment.table_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setTableNumber(Integer tableNumber) {
		this.tableNumber = tableNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.chart_bumber
	 * @return  the value of critical_assessment.chart_bumber
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public Integer getChartBumber() {
		return chartBumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.chart_bumber
	 * @param chartBumber  the value for critical_assessment.chart_bumber
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setChartBumber(Integer chartBumber) {
		this.chartBumber = chartBumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.drawing_board_number
	 * @return  the value of critical_assessment.drawing_board_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public Integer getDrawingBoardNumber() {
		return drawingBoardNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.drawing_board_number
	 * @param drawingBoardNumber  the value for critical_assessment.drawing_board_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setDrawingBoardNumber(Integer drawingBoardNumber) {
		this.drawingBoardNumber = drawingBoardNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.image_number
	 * @return  the value of critical_assessment.image_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public Integer getImageNumber() {
		return imageNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.image_number
	 * @param imageNumber  the value for critical_assessment.image_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setImageNumber(Integer imageNumber) {
		this.imageNumber = imageNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.document_number
	 * @return  the value of critical_assessment.document_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public Integer getDocumentNumber() {
		return documentNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.document_number
	 * @param documentNumber  the value for critical_assessment.document_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setDocumentNumber(Integer documentNumber) {
		this.documentNumber = documentNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.calculation_software_number
	 * @return  the value of critical_assessment.calculation_software_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public Integer getCalculationSoftwareNumber() {
		return calculationSoftwareNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.calculation_software_number
	 * @param calculationSoftwareNumber  the value for critical_assessment.calculation_software_number
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setCalculationSoftwareNumber(Integer calculationSoftwareNumber) {
		this.calculationSoftwareNumber = calculationSoftwareNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.layout
	 * @return  the value of critical_assessment.layout
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public String getLayout() {
		return layout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.layout
	 * @param layout  the value for critical_assessment.layout
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setLayout(String layout) {
		this.layout = layout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.writing
	 * @return  the value of critical_assessment.writing
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public String getWriting() {
		return writing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.writing
	 * @param writing  the value for critical_assessment.writing
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setWriting(String writing) {
		this.writing = writing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.technical_terms
	 * @return  the value of critical_assessment.technical_terms
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public String getTechnicalTerms() {
		return technicalTerms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.technical_terms
	 * @param technicalTerms  the value for critical_assessment.technical_terms
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setTechnicalTerms(String technicalTerms) {
		this.technicalTerms = technicalTerms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.advantage
	 * @return  the value of critical_assessment.advantage
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public String getAdvantage() {
		return advantage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.advantage
	 * @param advantage  the value for critical_assessment.advantage
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setAdvantage(String advantage) {
		this.advantage = advantage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.defect
	 * @return  the value of critical_assessment.defect
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public String getDefect() {
		return defect;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.defect
	 * @param defect  the value for critical_assessment.defect
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setDefect(String defect) {
		this.defect = defect;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.conclude
	 * @return  the value of critical_assessment.conclude
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public String getConclude() {
		return conclude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.conclude
	 * @param conclude  the value for critical_assessment.conclude
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setConclude(String conclude) {
		this.conclude = conclude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.suggestion
	 * @return  the value of critical_assessment.suggestion
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public Integer getSuggestion() {
		return suggestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.suggestion
	 * @param suggestion  the value for critical_assessment.suggestion
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setSuggestion(Integer suggestion) {
		this.suggestion = suggestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.is_deleted
	 * @return  the value of critical_assessment.is_deleted
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.is_deleted
	 * @param isDeleted  the value for critical_assessment.is_deleted
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.created_at
	 * @return  the value of critical_assessment.created_at
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public Long getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.created_at
	 * @param createdAt  the value for critical_assessment.created_at
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setCreatedAt(Long createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.updated_at
	 * @return  the value of critical_assessment.updated_at
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public Long getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.updated_at
	 * @param updatedAt  the value for critical_assessment.updated_at
	 * @mbg.generated  Sun Aug 13 22:33:45 ICT 2023
	 */
	public void setUpdatedAt(Long updatedAt) {
		this.updatedAt = updatedAt;
	}
}