package web.nl.kltn.model.generator;

public class CriticalAssessment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.thesis_id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private String thesisId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.content
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.analysis_results
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private String analysisResults;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.feedback_lecturer_question
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private String feedbackLecturerQuestion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.council_question
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private String councilQuestion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.behavior
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private String behavior;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.marker
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private String marker;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.is_deleted
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private Boolean isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.created_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private Long createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column critical_assessment.updated_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private Long updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.id
	 * @return  the value of critical_assessment.id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.id
	 * @param id  the value for critical_assessment.id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.thesis_id
	 * @return  the value of critical_assessment.thesis_id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public String getThesisId() {
		return thesisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.thesis_id
	 * @param thesisId  the value for critical_assessment.thesis_id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setThesisId(String thesisId) {
		this.thesisId = thesisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.content
	 * @return  the value of critical_assessment.content
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.content
	 * @param content  the value for critical_assessment.content
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.analysis_results
	 * @return  the value of critical_assessment.analysis_results
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public String getAnalysisResults() {
		return analysisResults;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.analysis_results
	 * @param analysisResults  the value for critical_assessment.analysis_results
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setAnalysisResults(String analysisResults) {
		this.analysisResults = analysisResults;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.feedback_lecturer_question
	 * @return  the value of critical_assessment.feedback_lecturer_question
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public String getFeedbackLecturerQuestion() {
		return feedbackLecturerQuestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.feedback_lecturer_question
	 * @param feedbackLecturerQuestion  the value for critical_assessment.feedback_lecturer_question
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setFeedbackLecturerQuestion(String feedbackLecturerQuestion) {
		this.feedbackLecturerQuestion = feedbackLecturerQuestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.council_question
	 * @return  the value of critical_assessment.council_question
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public String getCouncilQuestion() {
		return councilQuestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.council_question
	 * @param councilQuestion  the value for critical_assessment.council_question
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setCouncilQuestion(String councilQuestion) {
		this.councilQuestion = councilQuestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.behavior
	 * @return  the value of critical_assessment.behavior
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public String getBehavior() {
		return behavior;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.behavior
	 * @param behavior  the value for critical_assessment.behavior
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setBehavior(String behavior) {
		this.behavior = behavior;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.marker
	 * @return  the value of critical_assessment.marker
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public String getMarker() {
		return marker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.marker
	 * @param marker  the value for critical_assessment.marker
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setMarker(String marker) {
		this.marker = marker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.is_deleted
	 * @return  the value of critical_assessment.is_deleted
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.is_deleted
	 * @param isDeleted  the value for critical_assessment.is_deleted
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.created_at
	 * @return  the value of critical_assessment.created_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public Long getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.created_at
	 * @param createdAt  the value for critical_assessment.created_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setCreatedAt(Long createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column critical_assessment.updated_at
	 * @return  the value of critical_assessment.updated_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public Long getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column critical_assessment.updated_at
	 * @param updatedAt  the value for critical_assessment.updated_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setUpdatedAt(Long updatedAt) {
		this.updatedAt = updatedAt;
	}
}