package web.nl.kltn.model.generator;

public class DefenseRating {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating.id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating.thesis_id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private String thesisId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating.marker
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private String marker;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating.content_score
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private String contentScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating.analysis_result_score
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private String analysisResultScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating.feedback_lecturer_question_score
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private String feedbackLecturerQuestionScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating.council_question_score
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private String councilQuestionScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating.behavior_score
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private String behaviorScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating.is_deleted
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private Boolean isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating.created_at
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private Long createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating.updated_at
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private Long updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating.id
	 * @return  the value of defense_rating.id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating.id
	 * @param id  the value for defense_rating.id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating.thesis_id
	 * @return  the value of defense_rating.thesis_id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public String getThesisId() {
		return thesisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating.thesis_id
	 * @param thesisId  the value for defense_rating.thesis_id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setThesisId(String thesisId) {
		this.thesisId = thesisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating.marker
	 * @return  the value of defense_rating.marker
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public String getMarker() {
		return marker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating.marker
	 * @param marker  the value for defense_rating.marker
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setMarker(String marker) {
		this.marker = marker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating.content_score
	 * @return  the value of defense_rating.content_score
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public String getContentScore() {
		return contentScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating.content_score
	 * @param contentScore  the value for defense_rating.content_score
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setContentScore(String contentScore) {
		this.contentScore = contentScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating.analysis_result_score
	 * @return  the value of defense_rating.analysis_result_score
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public String getAnalysisResultScore() {
		return analysisResultScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating.analysis_result_score
	 * @param analysisResultScore  the value for defense_rating.analysis_result_score
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setAnalysisResultScore(String analysisResultScore) {
		this.analysisResultScore = analysisResultScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating.feedback_lecturer_question_score
	 * @return  the value of defense_rating.feedback_lecturer_question_score
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public String getFeedbackLecturerQuestionScore() {
		return feedbackLecturerQuestionScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating.feedback_lecturer_question_score
	 * @param feedbackLecturerQuestionScore  the value for defense_rating.feedback_lecturer_question_score
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setFeedbackLecturerQuestionScore(String feedbackLecturerQuestionScore) {
		this.feedbackLecturerQuestionScore = feedbackLecturerQuestionScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating.council_question_score
	 * @return  the value of defense_rating.council_question_score
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public String getCouncilQuestionScore() {
		return councilQuestionScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating.council_question_score
	 * @param councilQuestionScore  the value for defense_rating.council_question_score
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setCouncilQuestionScore(String councilQuestionScore) {
		this.councilQuestionScore = councilQuestionScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating.behavior_score
	 * @return  the value of defense_rating.behavior_score
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public String getBehaviorScore() {
		return behaviorScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating.behavior_score
	 * @param behaviorScore  the value for defense_rating.behavior_score
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setBehaviorScore(String behaviorScore) {
		this.behaviorScore = behaviorScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating.is_deleted
	 * @return  the value of defense_rating.is_deleted
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating.is_deleted
	 * @param isDeleted  the value for defense_rating.is_deleted
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating.created_at
	 * @return  the value of defense_rating.created_at
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public Long getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating.created_at
	 * @param createdAt  the value for defense_rating.created_at
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setCreatedAt(Long createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating.updated_at
	 * @return  the value of defense_rating.updated_at
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public Long getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating.updated_at
	 * @param updatedAt  the value for defense_rating.updated_at
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setUpdatedAt(Long updatedAt) {
		this.updatedAt = updatedAt;
	}
}