package web.nl.kltn.model.generator;

public class DefenseRatingScore {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating_score.id
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating_score.dr_id
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	private String drId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating_score.student_id
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	private String studentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating_score.score_1
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	private Double score1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating_score.score_2
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	private Double score2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating_score.score_3
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	private Double score3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating_score.total_score
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	private Double totalScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating_score.is_deleted
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	private Boolean isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating_score.created_at
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	private Long createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column defense_rating_score.updated_at
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	private Long updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating_score.id
	 * @return  the value of defense_rating_score.id
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating_score.id
	 * @param id  the value for defense_rating_score.id
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating_score.dr_id
	 * @return  the value of defense_rating_score.dr_id
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public String getDrId() {
		return drId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating_score.dr_id
	 * @param drId  the value for defense_rating_score.dr_id
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public void setDrId(String drId) {
		this.drId = drId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating_score.student_id
	 * @return  the value of defense_rating_score.student_id
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public String getStudentId() {
		return studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating_score.student_id
	 * @param studentId  the value for defense_rating_score.student_id
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating_score.score_1
	 * @return  the value of defense_rating_score.score_1
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public Double getScore1() {
		return score1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating_score.score_1
	 * @param score1  the value for defense_rating_score.score_1
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public void setScore1(Double score1) {
		this.score1 = score1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating_score.score_2
	 * @return  the value of defense_rating_score.score_2
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public Double getScore2() {
		return score2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating_score.score_2
	 * @param score2  the value for defense_rating_score.score_2
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public void setScore2(Double score2) {
		this.score2 = score2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating_score.score_3
	 * @return  the value of defense_rating_score.score_3
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public Double getScore3() {
		return score3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating_score.score_3
	 * @param score3  the value for defense_rating_score.score_3
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public void setScore3(Double score3) {
		this.score3 = score3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating_score.total_score
	 * @return  the value of defense_rating_score.total_score
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public Double getTotalScore() {
		return totalScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating_score.total_score
	 * @param totalScore  the value for defense_rating_score.total_score
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public void setTotalScore(Double totalScore) {
		this.totalScore = totalScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating_score.is_deleted
	 * @return  the value of defense_rating_score.is_deleted
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating_score.is_deleted
	 * @param isDeleted  the value for defense_rating_score.is_deleted
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating_score.created_at
	 * @return  the value of defense_rating_score.created_at
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public Long getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating_score.created_at
	 * @param createdAt  the value for defense_rating_score.created_at
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public void setCreatedAt(Long createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column defense_rating_score.updated_at
	 * @return  the value of defense_rating_score.updated_at
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public Long getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column defense_rating_score.updated_at
	 * @param updatedAt  the value for defense_rating_score.updated_at
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public void setUpdatedAt(Long updatedAt) {
		this.updatedAt = updatedAt;
	}
}