package web.nl.kltn.model.generator;

public class Lecturer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lecturer.id
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lecturer.user_id
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lecturer.degree
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private String degree;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lecturer.title
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private String title;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lecturer.id
	 * @return  the value of lecturer.id
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lecturer.id
	 * @param id  the value for lecturer.id
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lecturer.user_id
	 * @return  the value of lecturer.user_id
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lecturer.user_id
	 * @param userId  the value for lecturer.user_id
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lecturer.degree
	 * @return  the value of lecturer.degree
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public String getDegree() {
		return degree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lecturer.degree
	 * @param degree  the value for lecturer.degree
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setDegree(String degree) {
		this.degree = degree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lecturer.title
	 * @return  the value of lecturer.title
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lecturer.title
	 * @param title  the value for lecturer.title
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setTitle(String title) {
		this.title = title;
	}
}