package web.nl.kltn.model.generator;

public class Leturer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column leturer.id
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column leturer.user_id
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column leturer.degree
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	private String degree;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column leturer.title
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	private String title;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column leturer.id
	 * @return  the value of leturer.id
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column leturer.id
	 * @param id  the value for leturer.id
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column leturer.user_id
	 * @return  the value of leturer.user_id
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column leturer.user_id
	 * @param userId  the value for leturer.user_id
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column leturer.degree
	 * @return  the value of leturer.degree
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public String getDegree() {
		return degree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column leturer.degree
	 * @param degree  the value for leturer.degree
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public void setDegree(String degree) {
		this.degree = degree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column leturer.title
	 * @return  the value of leturer.title
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column leturer.title
	 * @param title  the value for leturer.title
	 * @mbg.generated  Sun Aug 27 14:21:17 ICT 2023
	 */
	public void setTitle(String title) {
		this.title = title;
	}
}