package web.nl.kltn.model.generator;

public class NotificationAttachment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notification_attachment.id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notification_attachment.notification_id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private String notificationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notification_attachment.attachment_url
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private String attachmentUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notification_attachment.is_deleted
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private Boolean isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notification_attachment.create_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private Long createAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notification_attachment.update_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private Long updateAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notification_attachment.id
	 * @return  the value of notification_attachment.id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notification_attachment.id
	 * @param id  the value for notification_attachment.id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notification_attachment.notification_id
	 * @return  the value of notification_attachment.notification_id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public String getNotificationId() {
		return notificationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notification_attachment.notification_id
	 * @param notificationId  the value for notification_attachment.notification_id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setNotificationId(String notificationId) {
		this.notificationId = notificationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notification_attachment.attachment_url
	 * @return  the value of notification_attachment.attachment_url
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public String getAttachmentUrl() {
		return attachmentUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notification_attachment.attachment_url
	 * @param attachmentUrl  the value for notification_attachment.attachment_url
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setAttachmentUrl(String attachmentUrl) {
		this.attachmentUrl = attachmentUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notification_attachment.is_deleted
	 * @return  the value of notification_attachment.is_deleted
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notification_attachment.is_deleted
	 * @param isDeleted  the value for notification_attachment.is_deleted
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notification_attachment.create_at
	 * @return  the value of notification_attachment.create_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public Long getCreateAt() {
		return createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notification_attachment.create_at
	 * @param createAt  the value for notification_attachment.create_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setCreateAt(Long createAt) {
		this.createAt = createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notification_attachment.update_at
	 * @return  the value of notification_attachment.update_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public Long getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notification_attachment.update_at
	 * @param updateAt  the value for notification_attachment.update_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setUpdateAt(Long updateAt) {
		this.updateAt = updateAt;
	}
}