package web.nl.kltn.model.generator;

public class ProtectionRatingScore {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column protection_rating_score.id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column protection_rating_score.pr_id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private String prId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column protection_rating_score.student_id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private String studentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column protection_rating_score.score
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private Double score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column protection_rating_score.is_deleted
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private Boolean isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column protection_rating_score.created_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private Long createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column protection_rating_score.updated_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private Long updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column protection_rating_score.id
	 * @return  the value of protection_rating_score.id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column protection_rating_score.id
	 * @param id  the value for protection_rating_score.id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column protection_rating_score.pr_id
	 * @return  the value of protection_rating_score.pr_id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public String getPrId() {
		return prId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column protection_rating_score.pr_id
	 * @param prId  the value for protection_rating_score.pr_id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setPrId(String prId) {
		this.prId = prId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column protection_rating_score.student_id
	 * @return  the value of protection_rating_score.student_id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public String getStudentId() {
		return studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column protection_rating_score.student_id
	 * @param studentId  the value for protection_rating_score.student_id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column protection_rating_score.score
	 * @return  the value of protection_rating_score.score
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public Double getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column protection_rating_score.score
	 * @param score  the value for protection_rating_score.score
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setScore(Double score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column protection_rating_score.is_deleted
	 * @return  the value of protection_rating_score.is_deleted
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column protection_rating_score.is_deleted
	 * @param isDeleted  the value for protection_rating_score.is_deleted
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column protection_rating_score.created_at
	 * @return  the value of protection_rating_score.created_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public Long getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column protection_rating_score.created_at
	 * @param createdAt  the value for protection_rating_score.created_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setCreatedAt(Long createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column protection_rating_score.updated_at
	 * @return  the value of protection_rating_score.updated_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public Long getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column protection_rating_score.updated_at
	 * @param updatedAt  the value for protection_rating_score.updated_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setUpdatedAt(Long updatedAt) {
		this.updatedAt = updatedAt;
	}
}