package web.nl.kltn.model.generator;

public class ProtectionRatingQuestion {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column protection_rating_question.id
	 * @mbg.generated  Mon Jul 17 16:14:00 ICT 2023
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column protection_rating_question.pr_id
	 * @mbg.generated  Mon Jul 17 16:14:00 ICT 2023
	 */
	private String prId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column protection_rating_question.question
	 * @mbg.generated  Mon Jul 17 16:14:00 ICT 2023
	 */
	private String question;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column protection_rating_question.is_deleted
	 * @mbg.generated  Mon Jul 17 16:14:00 ICT 2023
	 */
	private Boolean isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column protection_rating_question.created_at
	 * @mbg.generated  Mon Jul 17 16:14:00 ICT 2023
	 */
	private Long createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column protection_rating_question.updated_at
	 * @mbg.generated  Mon Jul 17 16:14:00 ICT 2023
	 */
	private Long updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column protection_rating_question.id
	 * @return  the value of protection_rating_question.id
	 * @mbg.generated  Mon Jul 17 16:14:00 ICT 2023
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column protection_rating_question.id
	 * @param id  the value for protection_rating_question.id
	 * @mbg.generated  Mon Jul 17 16:14:00 ICT 2023
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column protection_rating_question.pr_id
	 * @return  the value of protection_rating_question.pr_id
	 * @mbg.generated  Mon Jul 17 16:14:00 ICT 2023
	 */
	public String getPrId() {
		return prId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column protection_rating_question.pr_id
	 * @param prId  the value for protection_rating_question.pr_id
	 * @mbg.generated  Mon Jul 17 16:14:00 ICT 2023
	 */
	public void setPrId(String prId) {
		this.prId = prId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column protection_rating_question.question
	 * @return  the value of protection_rating_question.question
	 * @mbg.generated  Mon Jul 17 16:14:00 ICT 2023
	 */
	public String getQuestion() {
		return question;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column protection_rating_question.question
	 * @param question  the value for protection_rating_question.question
	 * @mbg.generated  Mon Jul 17 16:14:00 ICT 2023
	 */
	public void setQuestion(String question) {
		this.question = question;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column protection_rating_question.is_deleted
	 * @return  the value of protection_rating_question.is_deleted
	 * @mbg.generated  Mon Jul 17 16:14:00 ICT 2023
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column protection_rating_question.is_deleted
	 * @param isDeleted  the value for protection_rating_question.is_deleted
	 * @mbg.generated  Mon Jul 17 16:14:00 ICT 2023
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column protection_rating_question.created_at
	 * @return  the value of protection_rating_question.created_at
	 * @mbg.generated  Mon Jul 17 16:14:00 ICT 2023
	 */
	public Long getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column protection_rating_question.created_at
	 * @param createdAt  the value for protection_rating_question.created_at
	 * @mbg.generated  Mon Jul 17 16:14:00 ICT 2023
	 */
	public void setCreatedAt(Long createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column protection_rating_question.updated_at
	 * @return  the value of protection_rating_question.updated_at
	 * @mbg.generated  Mon Jul 17 16:14:00 ICT 2023
	 */
	public Long getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column protection_rating_question.updated_at
	 * @param updatedAt  the value for protection_rating_question.updated_at
	 * @mbg.generated  Mon Jul 17 16:14:00 ICT 2023
	 */
	public void setUpdatedAt(Long updatedAt) {
		this.updatedAt = updatedAt;
	}
}