package web.nl.kltn.model.generator;

import java.util.Date;

public class RefreshToken {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refresh_token.token
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private String token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refresh_token.user_id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refresh_token.expiration_date
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private Date expirationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refresh_token.create_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private Long createAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refresh_token.update_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private Long updateAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refresh_token.token
	 * @return  the value of refresh_token.token
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refresh_token.token
	 * @param token  the value for refresh_token.token
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refresh_token.user_id
	 * @return  the value of refresh_token.user_id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refresh_token.user_id
	 * @param userId  the value for refresh_token.user_id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refresh_token.expiration_date
	 * @return  the value of refresh_token.expiration_date
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public Date getExpirationDate() {
		return expirationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refresh_token.expiration_date
	 * @param expirationDate  the value for refresh_token.expiration_date
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refresh_token.create_at
	 * @return  the value of refresh_token.create_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public Long getCreateAt() {
		return createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refresh_token.create_at
	 * @param createAt  the value for refresh_token.create_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setCreateAt(Long createAt) {
		this.createAt = createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refresh_token.update_at
	 * @return  the value of refresh_token.update_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public Long getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refresh_token.update_at
	 * @param updateAt  the value for refresh_token.update_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setUpdateAt(Long updateAt) {
		this.updateAt = updateAt;
	}
}