package web.nl.kltn.model.generator;

import java.util.Date;

public class RefreshToken {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refresh_token.token
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	private String token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refresh_token.user_id
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refresh_token.expiration_date
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	private Date expirationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refresh_token.created_at
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	private Long createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refresh_token.updated_at
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	private Long updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refresh_token.token
	 * @return  the value of refresh_token.token
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refresh_token.token
	 * @param token  the value for refresh_token.token
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refresh_token.user_id
	 * @return  the value of refresh_token.user_id
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refresh_token.user_id
	 * @param userId  the value for refresh_token.user_id
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refresh_token.expiration_date
	 * @return  the value of refresh_token.expiration_date
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public Date getExpirationDate() {
		return expirationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refresh_token.expiration_date
	 * @param expirationDate  the value for refresh_token.expiration_date
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refresh_token.created_at
	 * @return  the value of refresh_token.created_at
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public Long getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refresh_token.created_at
	 * @param createdAt  the value for refresh_token.created_at
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public void setCreatedAt(Long createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refresh_token.updated_at
	 * @return  the value of refresh_token.updated_at
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public Long getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refresh_token.updated_at
	 * @param updatedAt  the value for refresh_token.updated_at
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public void setUpdatedAt(Long updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Override
	public String toString() {
		return "RefreshToken [token=" + token + ", userId=" + userId + ", expirationDate=" + expirationDate
				+ ", createdAt=" + createdAt + ", updatedAt=" + updatedAt + "]";
	}
}