package web.nl.kltn.model.generator;

public class RefreshToken {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refresh_token.token
	 * @mbg.generated  Sat May 13 11:00:18 ICT 2023
	 */
	private String token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column refresh_token.user_id
	 * @mbg.generated  Sat May 13 11:00:18 ICT 2023
	 */
	private String userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refresh_token.token
	 * @return  the value of refresh_token.token
	 * @mbg.generated  Sat May 13 11:00:18 ICT 2023
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refresh_token.token
	 * @param token  the value for refresh_token.token
	 * @mbg.generated  Sat May 13 11:00:18 ICT 2023
	 */
	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column refresh_token.user_id
	 * @return  the value of refresh_token.user_id
	 * @mbg.generated  Sat May 13 11:00:18 ICT 2023
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column refresh_token.user_id
	 * @param userId  the value for refresh_token.user_id
	 * @mbg.generated  Sat May 13 11:00:18 ICT 2023
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}
}