package web.nl.kltn.model.generator;

import java.util.ArrayList;
import java.util.List;

public class ReviewerExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table reviewer
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table reviewer
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table reviewer
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public ReviewerExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reviewer
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table reviewer
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andThesisIdIsNull() {
			addCriterion("thesis_id is null");
			return (Criteria) this;
		}

		public Criteria andThesisIdIsNotNull() {
			addCriterion("thesis_id is not null");
			return (Criteria) this;
		}

		public Criteria andThesisIdEqualTo(String value) {
			addCriterion("thesis_id =", value, "thesisId");
			return (Criteria) this;
		}

		public Criteria andThesisIdNotEqualTo(String value) {
			addCriterion("thesis_id <>", value, "thesisId");
			return (Criteria) this;
		}

		public Criteria andThesisIdGreaterThan(String value) {
			addCriterion("thesis_id >", value, "thesisId");
			return (Criteria) this;
		}

		public Criteria andThesisIdGreaterThanOrEqualTo(String value) {
			addCriterion("thesis_id >=", value, "thesisId");
			return (Criteria) this;
		}

		public Criteria andThesisIdLessThan(String value) {
			addCriterion("thesis_id <", value, "thesisId");
			return (Criteria) this;
		}

		public Criteria andThesisIdLessThanOrEqualTo(String value) {
			addCriterion("thesis_id <=", value, "thesisId");
			return (Criteria) this;
		}

		public Criteria andThesisIdLike(String value) {
			addCriterion("thesis_id like", value, "thesisId");
			return (Criteria) this;
		}

		public Criteria andThesisIdNotLike(String value) {
			addCriterion("thesis_id not like", value, "thesisId");
			return (Criteria) this;
		}

		public Criteria andThesisIdIn(List<String> values) {
			addCriterion("thesis_id in", values, "thesisId");
			return (Criteria) this;
		}

		public Criteria andThesisIdNotIn(List<String> values) {
			addCriterion("thesis_id not in", values, "thesisId");
			return (Criteria) this;
		}

		public Criteria andThesisIdBetween(String value1, String value2) {
			addCriterion("thesis_id between", value1, value2, "thesisId");
			return (Criteria) this;
		}

		public Criteria andThesisIdNotBetween(String value1, String value2) {
			addCriterion("thesis_id not between", value1, value2, "thesisId");
			return (Criteria) this;
		}

		public Criteria andMarkerIsNull() {
			addCriterion("marker is null");
			return (Criteria) this;
		}

		public Criteria andMarkerIsNotNull() {
			addCriterion("marker is not null");
			return (Criteria) this;
		}

		public Criteria andMarkerEqualTo(String value) {
			addCriterion("marker =", value, "marker");
			return (Criteria) this;
		}

		public Criteria andMarkerNotEqualTo(String value) {
			addCriterion("marker <>", value, "marker");
			return (Criteria) this;
		}

		public Criteria andMarkerGreaterThan(String value) {
			addCriterion("marker >", value, "marker");
			return (Criteria) this;
		}

		public Criteria andMarkerGreaterThanOrEqualTo(String value) {
			addCriterion("marker >=", value, "marker");
			return (Criteria) this;
		}

		public Criteria andMarkerLessThan(String value) {
			addCriterion("marker <", value, "marker");
			return (Criteria) this;
		}

		public Criteria andMarkerLessThanOrEqualTo(String value) {
			addCriterion("marker <=", value, "marker");
			return (Criteria) this;
		}

		public Criteria andMarkerLike(String value) {
			addCriterion("marker like", value, "marker");
			return (Criteria) this;
		}

		public Criteria andMarkerNotLike(String value) {
			addCriterion("marker not like", value, "marker");
			return (Criteria) this;
		}

		public Criteria andMarkerIn(List<String> values) {
			addCriterion("marker in", values, "marker");
			return (Criteria) this;
		}

		public Criteria andMarkerNotIn(List<String> values) {
			addCriterion("marker not in", values, "marker");
			return (Criteria) this;
		}

		public Criteria andMarkerBetween(String value1, String value2) {
			addCriterion("marker between", value1, value2, "marker");
			return (Criteria) this;
		}

		public Criteria andMarkerNotBetween(String value1, String value2) {
			addCriterion("marker not between", value1, value2, "marker");
			return (Criteria) this;
		}

		public Criteria andPageNumberIsNull() {
			addCriterion("page_number is null");
			return (Criteria) this;
		}

		public Criteria andPageNumberIsNotNull() {
			addCriterion("page_number is not null");
			return (Criteria) this;
		}

		public Criteria andPageNumberEqualTo(Integer value) {
			addCriterion("page_number =", value, "pageNumber");
			return (Criteria) this;
		}

		public Criteria andPageNumberNotEqualTo(Integer value) {
			addCriterion("page_number <>", value, "pageNumber");
			return (Criteria) this;
		}

		public Criteria andPageNumberGreaterThan(Integer value) {
			addCriterion("page_number >", value, "pageNumber");
			return (Criteria) this;
		}

		public Criteria andPageNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("page_number >=", value, "pageNumber");
			return (Criteria) this;
		}

		public Criteria andPageNumberLessThan(Integer value) {
			addCriterion("page_number <", value, "pageNumber");
			return (Criteria) this;
		}

		public Criteria andPageNumberLessThanOrEqualTo(Integer value) {
			addCriterion("page_number <=", value, "pageNumber");
			return (Criteria) this;
		}

		public Criteria andPageNumberIn(List<Integer> values) {
			addCriterion("page_number in", values, "pageNumber");
			return (Criteria) this;
		}

		public Criteria andPageNumberNotIn(List<Integer> values) {
			addCriterion("page_number not in", values, "pageNumber");
			return (Criteria) this;
		}

		public Criteria andPageNumberBetween(Integer value1, Integer value2) {
			addCriterion("page_number between", value1, value2, "pageNumber");
			return (Criteria) this;
		}

		public Criteria andPageNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("page_number not between", value1, value2, "pageNumber");
			return (Criteria) this;
		}

		public Criteria andChapterNumberIsNull() {
			addCriterion("chapter_number is null");
			return (Criteria) this;
		}

		public Criteria andChapterNumberIsNotNull() {
			addCriterion("chapter_number is not null");
			return (Criteria) this;
		}

		public Criteria andChapterNumberEqualTo(Integer value) {
			addCriterion("chapter_number =", value, "chapterNumber");
			return (Criteria) this;
		}

		public Criteria andChapterNumberNotEqualTo(Integer value) {
			addCriterion("chapter_number <>", value, "chapterNumber");
			return (Criteria) this;
		}

		public Criteria andChapterNumberGreaterThan(Integer value) {
			addCriterion("chapter_number >", value, "chapterNumber");
			return (Criteria) this;
		}

		public Criteria andChapterNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("chapter_number >=", value, "chapterNumber");
			return (Criteria) this;
		}

		public Criteria andChapterNumberLessThan(Integer value) {
			addCriterion("chapter_number <", value, "chapterNumber");
			return (Criteria) this;
		}

		public Criteria andChapterNumberLessThanOrEqualTo(Integer value) {
			addCriterion("chapter_number <=", value, "chapterNumber");
			return (Criteria) this;
		}

		public Criteria andChapterNumberIn(List<Integer> values) {
			addCriterion("chapter_number in", values, "chapterNumber");
			return (Criteria) this;
		}

		public Criteria andChapterNumberNotIn(List<Integer> values) {
			addCriterion("chapter_number not in", values, "chapterNumber");
			return (Criteria) this;
		}

		public Criteria andChapterNumberBetween(Integer value1, Integer value2) {
			addCriterion("chapter_number between", value1, value2, "chapterNumber");
			return (Criteria) this;
		}

		public Criteria andChapterNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("chapter_number not between", value1, value2, "chapterNumber");
			return (Criteria) this;
		}

		public Criteria andTableNumberIsNull() {
			addCriterion("table_number is null");
			return (Criteria) this;
		}

		public Criteria andTableNumberIsNotNull() {
			addCriterion("table_number is not null");
			return (Criteria) this;
		}

		public Criteria andTableNumberEqualTo(Integer value) {
			addCriterion("table_number =", value, "tableNumber");
			return (Criteria) this;
		}

		public Criteria andTableNumberNotEqualTo(Integer value) {
			addCriterion("table_number <>", value, "tableNumber");
			return (Criteria) this;
		}

		public Criteria andTableNumberGreaterThan(Integer value) {
			addCriterion("table_number >", value, "tableNumber");
			return (Criteria) this;
		}

		public Criteria andTableNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("table_number >=", value, "tableNumber");
			return (Criteria) this;
		}

		public Criteria andTableNumberLessThan(Integer value) {
			addCriterion("table_number <", value, "tableNumber");
			return (Criteria) this;
		}

		public Criteria andTableNumberLessThanOrEqualTo(Integer value) {
			addCriterion("table_number <=", value, "tableNumber");
			return (Criteria) this;
		}

		public Criteria andTableNumberIn(List<Integer> values) {
			addCriterion("table_number in", values, "tableNumber");
			return (Criteria) this;
		}

		public Criteria andTableNumberNotIn(List<Integer> values) {
			addCriterion("table_number not in", values, "tableNumber");
			return (Criteria) this;
		}

		public Criteria andTableNumberBetween(Integer value1, Integer value2) {
			addCriterion("table_number between", value1, value2, "tableNumber");
			return (Criteria) this;
		}

		public Criteria andTableNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("table_number not between", value1, value2, "tableNumber");
			return (Criteria) this;
		}

		public Criteria andChartNumberIsNull() {
			addCriterion("chart_number is null");
			return (Criteria) this;
		}

		public Criteria andChartNumberIsNotNull() {
			addCriterion("chart_number is not null");
			return (Criteria) this;
		}

		public Criteria andChartNumberEqualTo(Integer value) {
			addCriterion("chart_number =", value, "chartNumber");
			return (Criteria) this;
		}

		public Criteria andChartNumberNotEqualTo(Integer value) {
			addCriterion("chart_number <>", value, "chartNumber");
			return (Criteria) this;
		}

		public Criteria andChartNumberGreaterThan(Integer value) {
			addCriterion("chart_number >", value, "chartNumber");
			return (Criteria) this;
		}

		public Criteria andChartNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("chart_number >=", value, "chartNumber");
			return (Criteria) this;
		}

		public Criteria andChartNumberLessThan(Integer value) {
			addCriterion("chart_number <", value, "chartNumber");
			return (Criteria) this;
		}

		public Criteria andChartNumberLessThanOrEqualTo(Integer value) {
			addCriterion("chart_number <=", value, "chartNumber");
			return (Criteria) this;
		}

		public Criteria andChartNumberIn(List<Integer> values) {
			addCriterion("chart_number in", values, "chartNumber");
			return (Criteria) this;
		}

		public Criteria andChartNumberNotIn(List<Integer> values) {
			addCriterion("chart_number not in", values, "chartNumber");
			return (Criteria) this;
		}

		public Criteria andChartNumberBetween(Integer value1, Integer value2) {
			addCriterion("chart_number between", value1, value2, "chartNumber");
			return (Criteria) this;
		}

		public Criteria andChartNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("chart_number not between", value1, value2, "chartNumber");
			return (Criteria) this;
		}

		public Criteria andDrawingBoardNumberIsNull() {
			addCriterion("drawing_board_number is null");
			return (Criteria) this;
		}

		public Criteria andDrawingBoardNumberIsNotNull() {
			addCriterion("drawing_board_number is not null");
			return (Criteria) this;
		}

		public Criteria andDrawingBoardNumberEqualTo(Integer value) {
			addCriterion("drawing_board_number =", value, "drawingBoardNumber");
			return (Criteria) this;
		}

		public Criteria andDrawingBoardNumberNotEqualTo(Integer value) {
			addCriterion("drawing_board_number <>", value, "drawingBoardNumber");
			return (Criteria) this;
		}

		public Criteria andDrawingBoardNumberGreaterThan(Integer value) {
			addCriterion("drawing_board_number >", value, "drawingBoardNumber");
			return (Criteria) this;
		}

		public Criteria andDrawingBoardNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("drawing_board_number >=", value, "drawingBoardNumber");
			return (Criteria) this;
		}

		public Criteria andDrawingBoardNumberLessThan(Integer value) {
			addCriterion("drawing_board_number <", value, "drawingBoardNumber");
			return (Criteria) this;
		}

		public Criteria andDrawingBoardNumberLessThanOrEqualTo(Integer value) {
			addCriterion("drawing_board_number <=", value, "drawingBoardNumber");
			return (Criteria) this;
		}

		public Criteria andDrawingBoardNumberIn(List<Integer> values) {
			addCriterion("drawing_board_number in", values, "drawingBoardNumber");
			return (Criteria) this;
		}

		public Criteria andDrawingBoardNumberNotIn(List<Integer> values) {
			addCriterion("drawing_board_number not in", values, "drawingBoardNumber");
			return (Criteria) this;
		}

		public Criteria andDrawingBoardNumberBetween(Integer value1, Integer value2) {
			addCriterion("drawing_board_number between", value1, value2, "drawingBoardNumber");
			return (Criteria) this;
		}

		public Criteria andDrawingBoardNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("drawing_board_number not between", value1, value2, "drawingBoardNumber");
			return (Criteria) this;
		}

		public Criteria andImageNumberIsNull() {
			addCriterion("image_number is null");
			return (Criteria) this;
		}

		public Criteria andImageNumberIsNotNull() {
			addCriterion("image_number is not null");
			return (Criteria) this;
		}

		public Criteria andImageNumberEqualTo(Integer value) {
			addCriterion("image_number =", value, "imageNumber");
			return (Criteria) this;
		}

		public Criteria andImageNumberNotEqualTo(Integer value) {
			addCriterion("image_number <>", value, "imageNumber");
			return (Criteria) this;
		}

		public Criteria andImageNumberGreaterThan(Integer value) {
			addCriterion("image_number >", value, "imageNumber");
			return (Criteria) this;
		}

		public Criteria andImageNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("image_number >=", value, "imageNumber");
			return (Criteria) this;
		}

		public Criteria andImageNumberLessThan(Integer value) {
			addCriterion("image_number <", value, "imageNumber");
			return (Criteria) this;
		}

		public Criteria andImageNumberLessThanOrEqualTo(Integer value) {
			addCriterion("image_number <=", value, "imageNumber");
			return (Criteria) this;
		}

		public Criteria andImageNumberIn(List<Integer> values) {
			addCriterion("image_number in", values, "imageNumber");
			return (Criteria) this;
		}

		public Criteria andImageNumberNotIn(List<Integer> values) {
			addCriterion("image_number not in", values, "imageNumber");
			return (Criteria) this;
		}

		public Criteria andImageNumberBetween(Integer value1, Integer value2) {
			addCriterion("image_number between", value1, value2, "imageNumber");
			return (Criteria) this;
		}

		public Criteria andImageNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("image_number not between", value1, value2, "imageNumber");
			return (Criteria) this;
		}

		public Criteria andDocumentNumberIsNull() {
			addCriterion("document_number is null");
			return (Criteria) this;
		}

		public Criteria andDocumentNumberIsNotNull() {
			addCriterion("document_number is not null");
			return (Criteria) this;
		}

		public Criteria andDocumentNumberEqualTo(Integer value) {
			addCriterion("document_number =", value, "documentNumber");
			return (Criteria) this;
		}

		public Criteria andDocumentNumberNotEqualTo(Integer value) {
			addCriterion("document_number <>", value, "documentNumber");
			return (Criteria) this;
		}

		public Criteria andDocumentNumberGreaterThan(Integer value) {
			addCriterion("document_number >", value, "documentNumber");
			return (Criteria) this;
		}

		public Criteria andDocumentNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("document_number >=", value, "documentNumber");
			return (Criteria) this;
		}

		public Criteria andDocumentNumberLessThan(Integer value) {
			addCriterion("document_number <", value, "documentNumber");
			return (Criteria) this;
		}

		public Criteria andDocumentNumberLessThanOrEqualTo(Integer value) {
			addCriterion("document_number <=", value, "documentNumber");
			return (Criteria) this;
		}

		public Criteria andDocumentNumberIn(List<Integer> values) {
			addCriterion("document_number in", values, "documentNumber");
			return (Criteria) this;
		}

		public Criteria andDocumentNumberNotIn(List<Integer> values) {
			addCriterion("document_number not in", values, "documentNumber");
			return (Criteria) this;
		}

		public Criteria andDocumentNumberBetween(Integer value1, Integer value2) {
			addCriterion("document_number between", value1, value2, "documentNumber");
			return (Criteria) this;
		}

		public Criteria andDocumentNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("document_number not between", value1, value2, "documentNumber");
			return (Criteria) this;
		}

		public Criteria andCalculationSoftwareNumberIsNull() {
			addCriterion("calculation_software_number is null");
			return (Criteria) this;
		}

		public Criteria andCalculationSoftwareNumberIsNotNull() {
			addCriterion("calculation_software_number is not null");
			return (Criteria) this;
		}

		public Criteria andCalculationSoftwareNumberEqualTo(Integer value) {
			addCriterion("calculation_software_number =", value, "calculationSoftwareNumber");
			return (Criteria) this;
		}

		public Criteria andCalculationSoftwareNumberNotEqualTo(Integer value) {
			addCriterion("calculation_software_number <>", value, "calculationSoftwareNumber");
			return (Criteria) this;
		}

		public Criteria andCalculationSoftwareNumberGreaterThan(Integer value) {
			addCriterion("calculation_software_number >", value, "calculationSoftwareNumber");
			return (Criteria) this;
		}

		public Criteria andCalculationSoftwareNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("calculation_software_number >=", value, "calculationSoftwareNumber");
			return (Criteria) this;
		}

		public Criteria andCalculationSoftwareNumberLessThan(Integer value) {
			addCriterion("calculation_software_number <", value, "calculationSoftwareNumber");
			return (Criteria) this;
		}

		public Criteria andCalculationSoftwareNumberLessThanOrEqualTo(Integer value) {
			addCriterion("calculation_software_number <=", value, "calculationSoftwareNumber");
			return (Criteria) this;
		}

		public Criteria andCalculationSoftwareNumberIn(List<Integer> values) {
			addCriterion("calculation_software_number in", values, "calculationSoftwareNumber");
			return (Criteria) this;
		}

		public Criteria andCalculationSoftwareNumberNotIn(List<Integer> values) {
			addCriterion("calculation_software_number not in", values, "calculationSoftwareNumber");
			return (Criteria) this;
		}

		public Criteria andCalculationSoftwareNumberBetween(Integer value1, Integer value2) {
			addCriterion("calculation_software_number between", value1, value2, "calculationSoftwareNumber");
			return (Criteria) this;
		}

		public Criteria andCalculationSoftwareNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("calculation_software_number not between", value1, value2, "calculationSoftwareNumber");
			return (Criteria) this;
		}

		public Criteria andLayoutIsNull() {
			addCriterion("layout is null");
			return (Criteria) this;
		}

		public Criteria andLayoutIsNotNull() {
			addCriterion("layout is not null");
			return (Criteria) this;
		}

		public Criteria andLayoutEqualTo(String value) {
			addCriterion("layout =", value, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutNotEqualTo(String value) {
			addCriterion("layout <>", value, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutGreaterThan(String value) {
			addCriterion("layout >", value, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutGreaterThanOrEqualTo(String value) {
			addCriterion("layout >=", value, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutLessThan(String value) {
			addCriterion("layout <", value, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutLessThanOrEqualTo(String value) {
			addCriterion("layout <=", value, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutLike(String value) {
			addCriterion("layout like", value, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutNotLike(String value) {
			addCriterion("layout not like", value, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutIn(List<String> values) {
			addCriterion("layout in", values, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutNotIn(List<String> values) {
			addCriterion("layout not in", values, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutBetween(String value1, String value2) {
			addCriterion("layout between", value1, value2, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutNotBetween(String value1, String value2) {
			addCriterion("layout not between", value1, value2, "layout");
			return (Criteria) this;
		}

		public Criteria andWritingIsNull() {
			addCriterion("writing is null");
			return (Criteria) this;
		}

		public Criteria andWritingIsNotNull() {
			addCriterion("writing is not null");
			return (Criteria) this;
		}

		public Criteria andWritingEqualTo(String value) {
			addCriterion("writing =", value, "writing");
			return (Criteria) this;
		}

		public Criteria andWritingNotEqualTo(String value) {
			addCriterion("writing <>", value, "writing");
			return (Criteria) this;
		}

		public Criteria andWritingGreaterThan(String value) {
			addCriterion("writing >", value, "writing");
			return (Criteria) this;
		}

		public Criteria andWritingGreaterThanOrEqualTo(String value) {
			addCriterion("writing >=", value, "writing");
			return (Criteria) this;
		}

		public Criteria andWritingLessThan(String value) {
			addCriterion("writing <", value, "writing");
			return (Criteria) this;
		}

		public Criteria andWritingLessThanOrEqualTo(String value) {
			addCriterion("writing <=", value, "writing");
			return (Criteria) this;
		}

		public Criteria andWritingLike(String value) {
			addCriterion("writing like", value, "writing");
			return (Criteria) this;
		}

		public Criteria andWritingNotLike(String value) {
			addCriterion("writing not like", value, "writing");
			return (Criteria) this;
		}

		public Criteria andWritingIn(List<String> values) {
			addCriterion("writing in", values, "writing");
			return (Criteria) this;
		}

		public Criteria andWritingNotIn(List<String> values) {
			addCriterion("writing not in", values, "writing");
			return (Criteria) this;
		}

		public Criteria andWritingBetween(String value1, String value2) {
			addCriterion("writing between", value1, value2, "writing");
			return (Criteria) this;
		}

		public Criteria andWritingNotBetween(String value1, String value2) {
			addCriterion("writing not between", value1, value2, "writing");
			return (Criteria) this;
		}

		public Criteria andTechnicalTermsIsNull() {
			addCriterion("technical_terms is null");
			return (Criteria) this;
		}

		public Criteria andTechnicalTermsIsNotNull() {
			addCriterion("technical_terms is not null");
			return (Criteria) this;
		}

		public Criteria andTechnicalTermsEqualTo(String value) {
			addCriterion("technical_terms =", value, "technicalTerms");
			return (Criteria) this;
		}

		public Criteria andTechnicalTermsNotEqualTo(String value) {
			addCriterion("technical_terms <>", value, "technicalTerms");
			return (Criteria) this;
		}

		public Criteria andTechnicalTermsGreaterThan(String value) {
			addCriterion("technical_terms >", value, "technicalTerms");
			return (Criteria) this;
		}

		public Criteria andTechnicalTermsGreaterThanOrEqualTo(String value) {
			addCriterion("technical_terms >=", value, "technicalTerms");
			return (Criteria) this;
		}

		public Criteria andTechnicalTermsLessThan(String value) {
			addCriterion("technical_terms <", value, "technicalTerms");
			return (Criteria) this;
		}

		public Criteria andTechnicalTermsLessThanOrEqualTo(String value) {
			addCriterion("technical_terms <=", value, "technicalTerms");
			return (Criteria) this;
		}

		public Criteria andTechnicalTermsLike(String value) {
			addCriterion("technical_terms like", value, "technicalTerms");
			return (Criteria) this;
		}

		public Criteria andTechnicalTermsNotLike(String value) {
			addCriterion("technical_terms not like", value, "technicalTerms");
			return (Criteria) this;
		}

		public Criteria andTechnicalTermsIn(List<String> values) {
			addCriterion("technical_terms in", values, "technicalTerms");
			return (Criteria) this;
		}

		public Criteria andTechnicalTermsNotIn(List<String> values) {
			addCriterion("technical_terms not in", values, "technicalTerms");
			return (Criteria) this;
		}

		public Criteria andTechnicalTermsBetween(String value1, String value2) {
			addCriterion("technical_terms between", value1, value2, "technicalTerms");
			return (Criteria) this;
		}

		public Criteria andTechnicalTermsNotBetween(String value1, String value2) {
			addCriterion("technical_terms not between", value1, value2, "technicalTerms");
			return (Criteria) this;
		}

		public Criteria andAdvantageIsNull() {
			addCriterion("advantage is null");
			return (Criteria) this;
		}

		public Criteria andAdvantageIsNotNull() {
			addCriterion("advantage is not null");
			return (Criteria) this;
		}

		public Criteria andAdvantageEqualTo(String value) {
			addCriterion("advantage =", value, "advantage");
			return (Criteria) this;
		}

		public Criteria andAdvantageNotEqualTo(String value) {
			addCriterion("advantage <>", value, "advantage");
			return (Criteria) this;
		}

		public Criteria andAdvantageGreaterThan(String value) {
			addCriterion("advantage >", value, "advantage");
			return (Criteria) this;
		}

		public Criteria andAdvantageGreaterThanOrEqualTo(String value) {
			addCriterion("advantage >=", value, "advantage");
			return (Criteria) this;
		}

		public Criteria andAdvantageLessThan(String value) {
			addCriterion("advantage <", value, "advantage");
			return (Criteria) this;
		}

		public Criteria andAdvantageLessThanOrEqualTo(String value) {
			addCriterion("advantage <=", value, "advantage");
			return (Criteria) this;
		}

		public Criteria andAdvantageLike(String value) {
			addCriterion("advantage like", value, "advantage");
			return (Criteria) this;
		}

		public Criteria andAdvantageNotLike(String value) {
			addCriterion("advantage not like", value, "advantage");
			return (Criteria) this;
		}

		public Criteria andAdvantageIn(List<String> values) {
			addCriterion("advantage in", values, "advantage");
			return (Criteria) this;
		}

		public Criteria andAdvantageNotIn(List<String> values) {
			addCriterion("advantage not in", values, "advantage");
			return (Criteria) this;
		}

		public Criteria andAdvantageBetween(String value1, String value2) {
			addCriterion("advantage between", value1, value2, "advantage");
			return (Criteria) this;
		}

		public Criteria andAdvantageNotBetween(String value1, String value2) {
			addCriterion("advantage not between", value1, value2, "advantage");
			return (Criteria) this;
		}

		public Criteria andLimitationIsNull() {
			addCriterion("limitation is null");
			return (Criteria) this;
		}

		public Criteria andLimitationIsNotNull() {
			addCriterion("limitation is not null");
			return (Criteria) this;
		}

		public Criteria andLimitationEqualTo(String value) {
			addCriterion("limitation =", value, "limitation");
			return (Criteria) this;
		}

		public Criteria andLimitationNotEqualTo(String value) {
			addCriterion("limitation <>", value, "limitation");
			return (Criteria) this;
		}

		public Criteria andLimitationGreaterThan(String value) {
			addCriterion("limitation >", value, "limitation");
			return (Criteria) this;
		}

		public Criteria andLimitationGreaterThanOrEqualTo(String value) {
			addCriterion("limitation >=", value, "limitation");
			return (Criteria) this;
		}

		public Criteria andLimitationLessThan(String value) {
			addCriterion("limitation <", value, "limitation");
			return (Criteria) this;
		}

		public Criteria andLimitationLessThanOrEqualTo(String value) {
			addCriterion("limitation <=", value, "limitation");
			return (Criteria) this;
		}

		public Criteria andLimitationLike(String value) {
			addCriterion("limitation like", value, "limitation");
			return (Criteria) this;
		}

		public Criteria andLimitationNotLike(String value) {
			addCriterion("limitation not like", value, "limitation");
			return (Criteria) this;
		}

		public Criteria andLimitationIn(List<String> values) {
			addCriterion("limitation in", values, "limitation");
			return (Criteria) this;
		}

		public Criteria andLimitationNotIn(List<String> values) {
			addCriterion("limitation not in", values, "limitation");
			return (Criteria) this;
		}

		public Criteria andLimitationBetween(String value1, String value2) {
			addCriterion("limitation between", value1, value2, "limitation");
			return (Criteria) this;
		}

		public Criteria andLimitationNotBetween(String value1, String value2) {
			addCriterion("limitation not between", value1, value2, "limitation");
			return (Criteria) this;
		}

		public Criteria andConcludeIsNull() {
			addCriterion("conclude is null");
			return (Criteria) this;
		}

		public Criteria andConcludeIsNotNull() {
			addCriterion("conclude is not null");
			return (Criteria) this;
		}

		public Criteria andConcludeEqualTo(String value) {
			addCriterion("conclude =", value, "conclude");
			return (Criteria) this;
		}

		public Criteria andConcludeNotEqualTo(String value) {
			addCriterion("conclude <>", value, "conclude");
			return (Criteria) this;
		}

		public Criteria andConcludeGreaterThan(String value) {
			addCriterion("conclude >", value, "conclude");
			return (Criteria) this;
		}

		public Criteria andConcludeGreaterThanOrEqualTo(String value) {
			addCriterion("conclude >=", value, "conclude");
			return (Criteria) this;
		}

		public Criteria andConcludeLessThan(String value) {
			addCriterion("conclude <", value, "conclude");
			return (Criteria) this;
		}

		public Criteria andConcludeLessThanOrEqualTo(String value) {
			addCriterion("conclude <=", value, "conclude");
			return (Criteria) this;
		}

		public Criteria andConcludeLike(String value) {
			addCriterion("conclude like", value, "conclude");
			return (Criteria) this;
		}

		public Criteria andConcludeNotLike(String value) {
			addCriterion("conclude not like", value, "conclude");
			return (Criteria) this;
		}

		public Criteria andConcludeIn(List<String> values) {
			addCriterion("conclude in", values, "conclude");
			return (Criteria) this;
		}

		public Criteria andConcludeNotIn(List<String> values) {
			addCriterion("conclude not in", values, "conclude");
			return (Criteria) this;
		}

		public Criteria andConcludeBetween(String value1, String value2) {
			addCriterion("conclude between", value1, value2, "conclude");
			return (Criteria) this;
		}

		public Criteria andConcludeNotBetween(String value1, String value2) {
			addCriterion("conclude not between", value1, value2, "conclude");
			return (Criteria) this;
		}

		public Criteria andSuggestionIsNull() {
			addCriterion("suggestion is null");
			return (Criteria) this;
		}

		public Criteria andSuggestionIsNotNull() {
			addCriterion("suggestion is not null");
			return (Criteria) this;
		}

		public Criteria andSuggestionEqualTo(Integer value) {
			addCriterion("suggestion =", value, "suggestion");
			return (Criteria) this;
		}

		public Criteria andSuggestionNotEqualTo(Integer value) {
			addCriterion("suggestion <>", value, "suggestion");
			return (Criteria) this;
		}

		public Criteria andSuggestionGreaterThan(Integer value) {
			addCriterion("suggestion >", value, "suggestion");
			return (Criteria) this;
		}

		public Criteria andSuggestionGreaterThanOrEqualTo(Integer value) {
			addCriterion("suggestion >=", value, "suggestion");
			return (Criteria) this;
		}

		public Criteria andSuggestionLessThan(Integer value) {
			addCriterion("suggestion <", value, "suggestion");
			return (Criteria) this;
		}

		public Criteria andSuggestionLessThanOrEqualTo(Integer value) {
			addCriterion("suggestion <=", value, "suggestion");
			return (Criteria) this;
		}

		public Criteria andSuggestionIn(List<Integer> values) {
			addCriterion("suggestion in", values, "suggestion");
			return (Criteria) this;
		}

		public Criteria andSuggestionNotIn(List<Integer> values) {
			addCriterion("suggestion not in", values, "suggestion");
			return (Criteria) this;
		}

		public Criteria andSuggestionBetween(Integer value1, Integer value2) {
			addCriterion("suggestion between", value1, value2, "suggestion");
			return (Criteria) this;
		}

		public Criteria andSuggestionNotBetween(Integer value1, Integer value2) {
			addCriterion("suggestion not between", value1, value2, "suggestion");
			return (Criteria) this;
		}

		public Criteria andIsDeletedIsNull() {
			addCriterion("is_deleted is null");
			return (Criteria) this;
		}

		public Criteria andIsDeletedIsNotNull() {
			addCriterion("is_deleted is not null");
			return (Criteria) this;
		}

		public Criteria andIsDeletedEqualTo(Boolean value) {
			addCriterion("is_deleted =", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedNotEqualTo(Boolean value) {
			addCriterion("is_deleted <>", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedGreaterThan(Boolean value) {
			addCriterion("is_deleted >", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_deleted >=", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedLessThan(Boolean value) {
			addCriterion("is_deleted <", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedLessThanOrEqualTo(Boolean value) {
			addCriterion("is_deleted <=", value, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedIn(List<Boolean> values) {
			addCriterion("is_deleted in", values, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedNotIn(List<Boolean> values) {
			addCriterion("is_deleted not in", values, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedBetween(Boolean value1, Boolean value2) {
			addCriterion("is_deleted between", value1, value2, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andIsDeletedNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_deleted not between", value1, value2, "isDeleted");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNull() {
			addCriterion("created_at is null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNotNull() {
			addCriterion("created_at is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtEqualTo(Long value) {
			addCriterion("created_at =", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotEqualTo(Long value) {
			addCriterion("created_at <>", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThan(Long value) {
			addCriterion("created_at >", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThanOrEqualTo(Long value) {
			addCriterion("created_at >=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThan(Long value) {
			addCriterion("created_at <", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThanOrEqualTo(Long value) {
			addCriterion("created_at <=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIn(List<Long> values) {
			addCriterion("created_at in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotIn(List<Long> values) {
			addCriterion("created_at not in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtBetween(Long value1, Long value2) {
			addCriterion("created_at between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotBetween(Long value1, Long value2) {
			addCriterion("created_at not between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNull() {
			addCriterion("updated_at is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNotNull() {
			addCriterion("updated_at is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtEqualTo(Long value) {
			addCriterion("updated_at =", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotEqualTo(Long value) {
			addCriterion("updated_at <>", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThan(Long value) {
			addCriterion("updated_at >", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThanOrEqualTo(Long value) {
			addCriterion("updated_at >=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThan(Long value) {
			addCriterion("updated_at <", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThanOrEqualTo(Long value) {
			addCriterion("updated_at <=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIn(List<Long> values) {
			addCriterion("updated_at in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotIn(List<Long> values) {
			addCriterion("updated_at not in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtBetween(Long value1, Long value2) {
			addCriterion("updated_at between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotBetween(Long value1, Long value2) {
			addCriterion("updated_at not between", value1, value2, "updatedAt");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table reviewer
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reviewer
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 24 22:38:45 ICT 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}