package web.nl.kltn.model.generator;

public class Reviewer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.id
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.thesis_id
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private String thesisId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.marker
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private String marker;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.page_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private Integer pageNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.chapter_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private Integer chapterNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.table_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private Integer tableNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.chart_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private Integer chartNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.drawing_board_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private Integer drawingBoardNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.image_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private Integer imageNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.document_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private Integer documentNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.calculation_software_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private Integer calculationSoftwareNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.layout
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private String layout;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.writing
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private String writing;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.technical_terms
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private String technicalTerms;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.advantage
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private String advantage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.limitation
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private String limitation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.conclude
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private String conclude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.suggestion
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private Integer suggestion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.is_deleted
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private Boolean isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.created_at
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private Long createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reviewer.updated_at
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private Long updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.id
	 * @return  the value of reviewer.id
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.id
	 * @param id  the value for reviewer.id
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.thesis_id
	 * @return  the value of reviewer.thesis_id
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public String getThesisId() {
		return thesisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.thesis_id
	 * @param thesisId  the value for reviewer.thesis_id
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setThesisId(String thesisId) {
		this.thesisId = thesisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.marker
	 * @return  the value of reviewer.marker
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public String getMarker() {
		return marker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.marker
	 * @param marker  the value for reviewer.marker
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setMarker(String marker) {
		this.marker = marker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.page_number
	 * @return  the value of reviewer.page_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public Integer getPageNumber() {
		return pageNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.page_number
	 * @param pageNumber  the value for reviewer.page_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setPageNumber(Integer pageNumber) {
		this.pageNumber = pageNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.chapter_number
	 * @return  the value of reviewer.chapter_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public Integer getChapterNumber() {
		return chapterNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.chapter_number
	 * @param chapterNumber  the value for reviewer.chapter_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setChapterNumber(Integer chapterNumber) {
		this.chapterNumber = chapterNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.table_number
	 * @return  the value of reviewer.table_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public Integer getTableNumber() {
		return tableNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.table_number
	 * @param tableNumber  the value for reviewer.table_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setTableNumber(Integer tableNumber) {
		this.tableNumber = tableNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.chart_number
	 * @return  the value of reviewer.chart_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public Integer getChartNumber() {
		return chartNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.chart_number
	 * @param chartNumber  the value for reviewer.chart_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setChartNumber(Integer chartNumber) {
		this.chartNumber = chartNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.drawing_board_number
	 * @return  the value of reviewer.drawing_board_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public Integer getDrawingBoardNumber() {
		return drawingBoardNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.drawing_board_number
	 * @param drawingBoardNumber  the value for reviewer.drawing_board_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setDrawingBoardNumber(Integer drawingBoardNumber) {
		this.drawingBoardNumber = drawingBoardNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.image_number
	 * @return  the value of reviewer.image_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public Integer getImageNumber() {
		return imageNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.image_number
	 * @param imageNumber  the value for reviewer.image_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setImageNumber(Integer imageNumber) {
		this.imageNumber = imageNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.document_number
	 * @return  the value of reviewer.document_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public Integer getDocumentNumber() {
		return documentNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.document_number
	 * @param documentNumber  the value for reviewer.document_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setDocumentNumber(Integer documentNumber) {
		this.documentNumber = documentNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.calculation_software_number
	 * @return  the value of reviewer.calculation_software_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public Integer getCalculationSoftwareNumber() {
		return calculationSoftwareNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.calculation_software_number
	 * @param calculationSoftwareNumber  the value for reviewer.calculation_software_number
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setCalculationSoftwareNumber(Integer calculationSoftwareNumber) {
		this.calculationSoftwareNumber = calculationSoftwareNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.layout
	 * @return  the value of reviewer.layout
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public String getLayout() {
		return layout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.layout
	 * @param layout  the value for reviewer.layout
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setLayout(String layout) {
		this.layout = layout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.writing
	 * @return  the value of reviewer.writing
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public String getWriting() {
		return writing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.writing
	 * @param writing  the value for reviewer.writing
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setWriting(String writing) {
		this.writing = writing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.technical_terms
	 * @return  the value of reviewer.technical_terms
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public String getTechnicalTerms() {
		return technicalTerms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.technical_terms
	 * @param technicalTerms  the value for reviewer.technical_terms
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setTechnicalTerms(String technicalTerms) {
		this.technicalTerms = technicalTerms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.advantage
	 * @return  the value of reviewer.advantage
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public String getAdvantage() {
		return advantage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.advantage
	 * @param advantage  the value for reviewer.advantage
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setAdvantage(String advantage) {
		this.advantage = advantage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.limitation
	 * @return  the value of reviewer.limitation
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public String getLimitation() {
		return limitation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.limitation
	 * @param limitation  the value for reviewer.limitation
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setLimitation(String limitation) {
		this.limitation = limitation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.conclude
	 * @return  the value of reviewer.conclude
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public String getConclude() {
		return conclude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.conclude
	 * @param conclude  the value for reviewer.conclude
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setConclude(String conclude) {
		this.conclude = conclude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.suggestion
	 * @return  the value of reviewer.suggestion
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public Integer getSuggestion() {
		return suggestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.suggestion
	 * @param suggestion  the value for reviewer.suggestion
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setSuggestion(Integer suggestion) {
		this.suggestion = suggestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.is_deleted
	 * @return  the value of reviewer.is_deleted
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.is_deleted
	 * @param isDeleted  the value for reviewer.is_deleted
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.created_at
	 * @return  the value of reviewer.created_at
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public Long getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.created_at
	 * @param createdAt  the value for reviewer.created_at
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setCreatedAt(Long createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reviewer.updated_at
	 * @return  the value of reviewer.updated_at
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public Long getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reviewer.updated_at
	 * @param updatedAt  the value for reviewer.updated_at
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setUpdatedAt(Long updatedAt) {
		this.updatedAt = updatedAt;
	}
}