package web.nl.kltn.model.generator;

public class Role {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.role_id
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.role_name
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.is_deleted
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	private Boolean isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.created_at
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	private Long createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.updated_at
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	private Long updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.role_id
	 * @return  the value of role.role_id
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.role_id
	 * @param roleId  the value for role.role_id
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.role_name
	 * @return  the value of role.role_name
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.role_name
	 * @param roleName  the value for role.role_name
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.is_deleted
	 * @return  the value of role.is_deleted
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.is_deleted
	 * @param isDeleted  the value for role.is_deleted
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.created_at
	 * @return  the value of role.created_at
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public Long getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.created_at
	 * @param createdAt  the value for role.created_at
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public void setCreatedAt(Long createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.updated_at
	 * @return  the value of role.updated_at
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public Long getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.updated_at
	 * @param updatedAt  the value for role.updated_at
	 * @mbg.generated  Tue Aug 08 21:20:48 ICT 2023
	 */
	public void setUpdatedAt(Long updatedAt) {
		this.updatedAt = updatedAt;
	}
}