package web.nl.kltn.model.generator;

public class ThesisReviewerComment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_reviewer_comment.id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_reviewer_comment.thesis_id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private String thesisId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_reviewer_comment.user_id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_reviewer_comment.comment
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private String comment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_reviewer_comment.result
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private Integer result;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_reviewer_comment.is_general
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private Boolean isGeneral;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_reviewer_comment.is_deleted
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private Boolean isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_reviewer_comment.created_at
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private Long createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_reviewer_comment.updated_at
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private Long updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_reviewer_comment.id
	 * @return  the value of thesis_reviewer_comment.id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_reviewer_comment.id
	 * @param id  the value for thesis_reviewer_comment.id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_reviewer_comment.thesis_id
	 * @return  the value of thesis_reviewer_comment.thesis_id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public String getThesisId() {
		return thesisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_reviewer_comment.thesis_id
	 * @param thesisId  the value for thesis_reviewer_comment.thesis_id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setThesisId(String thesisId) {
		this.thesisId = thesisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_reviewer_comment.user_id
	 * @return  the value of thesis_reviewer_comment.user_id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_reviewer_comment.user_id
	 * @param userId  the value for thesis_reviewer_comment.user_id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_reviewer_comment.comment
	 * @return  the value of thesis_reviewer_comment.comment
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_reviewer_comment.comment
	 * @param comment  the value for thesis_reviewer_comment.comment
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_reviewer_comment.result
	 * @return  the value of thesis_reviewer_comment.result
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public Integer getResult() {
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_reviewer_comment.result
	 * @param result  the value for thesis_reviewer_comment.result
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setResult(Integer result) {
		this.result = result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_reviewer_comment.is_general
	 * @return  the value of thesis_reviewer_comment.is_general
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public Boolean getIsGeneral() {
		return isGeneral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_reviewer_comment.is_general
	 * @param isGeneral  the value for thesis_reviewer_comment.is_general
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setIsGeneral(Boolean isGeneral) {
		this.isGeneral = isGeneral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_reviewer_comment.is_deleted
	 * @return  the value of thesis_reviewer_comment.is_deleted
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_reviewer_comment.is_deleted
	 * @param isDeleted  the value for thesis_reviewer_comment.is_deleted
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_reviewer_comment.created_at
	 * @return  the value of thesis_reviewer_comment.created_at
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public Long getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_reviewer_comment.created_at
	 * @param createdAt  the value for thesis_reviewer_comment.created_at
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setCreatedAt(Long createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_reviewer_comment.updated_at
	 * @return  the value of thesis_reviewer_comment.updated_at
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public Long getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_reviewer_comment.updated_at
	 * @param updatedAt  the value for thesis_reviewer_comment.updated_at
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setUpdatedAt(Long updatedAt) {
		this.updatedAt = updatedAt;
	}
}