package web.nl.kltn.model.generator;

public class ThesisReviewCalendar {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_review_calendar.id
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_review_calendar.thesis_id
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private String thesisId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_review_calendar.start_at
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private Long startAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_review_calendar.end_at
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private Long endAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_review_calendar.is_deleted
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private Boolean isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_review_calendar.created_at
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private Long createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_review_calendar.updated_at
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	private Long updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_review_calendar.id
	 * @return  the value of thesis_review_calendar.id
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_review_calendar.id
	 * @param id  the value for thesis_review_calendar.id
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_review_calendar.thesis_id
	 * @return  the value of thesis_review_calendar.thesis_id
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public String getThesisId() {
		return thesisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_review_calendar.thesis_id
	 * @param thesisId  the value for thesis_review_calendar.thesis_id
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setThesisId(String thesisId) {
		this.thesisId = thesisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_review_calendar.start_at
	 * @return  the value of thesis_review_calendar.start_at
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public Long getStartAt() {
		return startAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_review_calendar.start_at
	 * @param startAt  the value for thesis_review_calendar.start_at
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setStartAt(Long startAt) {
		this.startAt = startAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_review_calendar.end_at
	 * @return  the value of thesis_review_calendar.end_at
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public Long getEndAt() {
		return endAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_review_calendar.end_at
	 * @param endAt  the value for thesis_review_calendar.end_at
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setEndAt(Long endAt) {
		this.endAt = endAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_review_calendar.is_deleted
	 * @return  the value of thesis_review_calendar.is_deleted
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_review_calendar.is_deleted
	 * @param isDeleted  the value for thesis_review_calendar.is_deleted
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_review_calendar.created_at
	 * @return  the value of thesis_review_calendar.created_at
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public Long getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_review_calendar.created_at
	 * @param createdAt  the value for thesis_review_calendar.created_at
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setCreatedAt(Long createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_review_calendar.updated_at
	 * @return  the value of thesis_review_calendar.updated_at
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public Long getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_review_calendar.updated_at
	 * @param updatedAt  the value for thesis_review_calendar.updated_at
	 * @mbg.generated  Sun Aug 27 18:00:43 ICT 2023
	 */
	public void setUpdatedAt(Long updatedAt) {
		this.updatedAt = updatedAt;
	}
}