package web.nl.kltn.model.generator;

public class Thesis {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis.id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis.topic
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private String topic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis.description
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis.year
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private Integer year;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis.semester
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private Integer semester;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis.status
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis.is_deleted
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private Boolean isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis.create_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private Long createAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis.update_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private Long updateAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis.id
	 * @return  the value of thesis.id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis.id
	 * @param id  the value for thesis.id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis.topic
	 * @return  the value of thesis.topic
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public String getTopic() {
		return topic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis.topic
	 * @param topic  the value for thesis.topic
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setTopic(String topic) {
		this.topic = topic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis.description
	 * @return  the value of thesis.description
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis.description
	 * @param description  the value for thesis.description
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis.year
	 * @return  the value of thesis.year
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public Integer getYear() {
		return year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis.year
	 * @param year  the value for thesis.year
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setYear(Integer year) {
		this.year = year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis.semester
	 * @return  the value of thesis.semester
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public Integer getSemester() {
		return semester;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis.semester
	 * @param semester  the value for thesis.semester
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setSemester(Integer semester) {
		this.semester = semester;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis.status
	 * @return  the value of thesis.status
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis.status
	 * @param status  the value for thesis.status
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis.is_deleted
	 * @return  the value of thesis.is_deleted
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis.is_deleted
	 * @param isDeleted  the value for thesis.is_deleted
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis.create_at
	 * @return  the value of thesis.create_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public Long getCreateAt() {
		return createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis.create_at
	 * @param createAt  the value for thesis.create_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setCreateAt(Long createAt) {
		this.createAt = createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis.update_at
	 * @return  the value of thesis.update_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public Long getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis.update_at
	 * @param updateAt  the value for thesis.update_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setUpdateAt(Long updateAt) {
		this.updateAt = updateAt;
	}
}