package web.nl.kltn.model.generator;

public class ThesisDocument {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_document.id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_document.thesis_id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private String thesisId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_document.file_url
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private String fileUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_document.type
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_document.is_deleted
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private Boolean isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_document.created_at
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private Long createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_document.updated_at
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	private Long updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_document.id
	 * @return  the value of thesis_document.id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_document.id
	 * @param id  the value for thesis_document.id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_document.thesis_id
	 * @return  the value of thesis_document.thesis_id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public String getThesisId() {
		return thesisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_document.thesis_id
	 * @param thesisId  the value for thesis_document.thesis_id
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setThesisId(String thesisId) {
		this.thesisId = thesisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_document.file_url
	 * @return  the value of thesis_document.file_url
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public String getFileUrl() {
		return fileUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_document.file_url
	 * @param fileUrl  the value for thesis_document.file_url
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_document.type
	 * @return  the value of thesis_document.type
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_document.type
	 * @param type  the value for thesis_document.type
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_document.is_deleted
	 * @return  the value of thesis_document.is_deleted
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_document.is_deleted
	 * @param isDeleted  the value for thesis_document.is_deleted
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_document.created_at
	 * @return  the value of thesis_document.created_at
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public Long getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_document.created_at
	 * @param createdAt  the value for thesis_document.created_at
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setCreatedAt(Long createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_document.updated_at
	 * @return  the value of thesis_document.updated_at
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public Long getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_document.updated_at
	 * @param updatedAt  the value for thesis_document.updated_at
	 * @mbg.generated  Sun Aug 27 07:37:56 ICT 2023
	 */
	public void setUpdatedAt(Long updatedAt) {
		this.updatedAt = updatedAt;
	}
}