package web.nl.kltn.model.generator;

public class ThesisUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_user.id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_user.thesis_id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private String thesisId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_user.user_id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_user.type
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_user.is_deleted
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private Boolean isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_user.created_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private Long createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_user.updated_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private Long updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_user.id
	 * @return  the value of thesis_user.id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_user.id
	 * @param id  the value for thesis_user.id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_user.thesis_id
	 * @return  the value of thesis_user.thesis_id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public String getThesisId() {
		return thesisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_user.thesis_id
	 * @param thesisId  the value for thesis_user.thesis_id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setThesisId(String thesisId) {
		this.thesisId = thesisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_user.user_id
	 * @return  the value of thesis_user.user_id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_user.user_id
	 * @param userId  the value for thesis_user.user_id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_user.type
	 * @return  the value of thesis_user.type
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_user.type
	 * @param type  the value for thesis_user.type
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_user.is_deleted
	 * @return  the value of thesis_user.is_deleted
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_user.is_deleted
	 * @param isDeleted  the value for thesis_user.is_deleted
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_user.created_at
	 * @return  the value of thesis_user.created_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public Long getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_user.created_at
	 * @param createdAt  the value for thesis_user.created_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setCreatedAt(Long createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_user.updated_at
	 * @return  the value of thesis_user.updated_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public Long getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_user.updated_at
	 * @param updatedAt  the value for thesis_user.updated_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setUpdatedAt(Long updatedAt) {
		this.updatedAt = updatedAt;
	}
}