package web.nl.kltn.model.generator;

public class Thesis {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis.id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis.topic
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private String topic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis.descriptio
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private String descriptio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis.year
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private Integer year;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis.semester
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private Integer semester;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis.status
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis.is_deleted
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private Boolean isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis.created_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private Long createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis.updated_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	private Long updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis.id
	 * @return  the value of thesis.id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis.id
	 * @param id  the value for thesis.id
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis.topic
	 * @return  the value of thesis.topic
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public String getTopic() {
		return topic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis.topic
	 * @param topic  the value for thesis.topic
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setTopic(String topic) {
		this.topic = topic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis.descriptio
	 * @return  the value of thesis.descriptio
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public String getDescriptio() {
		return descriptio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis.descriptio
	 * @param descriptio  the value for thesis.descriptio
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setDescriptio(String descriptio) {
		this.descriptio = descriptio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis.year
	 * @return  the value of thesis.year
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public Integer getYear() {
		return year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis.year
	 * @param year  the value for thesis.year
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setYear(Integer year) {
		this.year = year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis.semester
	 * @return  the value of thesis.semester
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public Integer getSemester() {
		return semester;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis.semester
	 * @param semester  the value for thesis.semester
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setSemester(Integer semester) {
		this.semester = semester;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis.status
	 * @return  the value of thesis.status
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis.status
	 * @param status  the value for thesis.status
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis.is_deleted
	 * @return  the value of thesis.is_deleted
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis.is_deleted
	 * @param isDeleted  the value for thesis.is_deleted
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis.created_at
	 * @return  the value of thesis.created_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public Long getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis.created_at
	 * @param createdAt  the value for thesis.created_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setCreatedAt(Long createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis.updated_at
	 * @return  the value of thesis.updated_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public Long getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis.updated_at
	 * @param updatedAt  the value for thesis.updated_at
	 * @mbg.generated  Sat Jul 08 20:39:31 ICT 2023
	 */
	public void setUpdatedAt(Long updatedAt) {
		this.updatedAt = updatedAt;
	}
}