package web.nl.kltn.model.generator;

public class ThesisUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_user.id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_user.thesis_id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private String thesisId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_user.user_id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_user.type
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_user.is_deleted
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private Boolean isDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_user.create_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private Long createAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column thesis_user.update_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	private Long updateAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_user.id
	 * @return  the value of thesis_user.id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_user.id
	 * @param id  the value for thesis_user.id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_user.thesis_id
	 * @return  the value of thesis_user.thesis_id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public String getThesisId() {
		return thesisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_user.thesis_id
	 * @param thesisId  the value for thesis_user.thesis_id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setThesisId(String thesisId) {
		this.thesisId = thesisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_user.user_id
	 * @return  the value of thesis_user.user_id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_user.user_id
	 * @param userId  the value for thesis_user.user_id
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_user.type
	 * @return  the value of thesis_user.type
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_user.type
	 * @param type  the value for thesis_user.type
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_user.is_deleted
	 * @return  the value of thesis_user.is_deleted
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public Boolean getIsDeleted() {
		return isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_user.is_deleted
	 * @param isDeleted  the value for thesis_user.is_deleted
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_user.create_at
	 * @return  the value of thesis_user.create_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public Long getCreateAt() {
		return createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_user.create_at
	 * @param createAt  the value for thesis_user.create_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setCreateAt(Long createAt) {
		this.createAt = createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column thesis_user.update_at
	 * @return  the value of thesis_user.update_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public Long getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column thesis_user.update_at
	 * @param updateAt  the value for thesis_user.update_at
	 * @mbg.generated  Mon Jun 26 22:27:07 ICT 2023
	 */
	public void setUpdateAt(Long updateAt) {
		this.updateAt = updateAt;
	}
}