package web.nl.kltn.model.generator;

public class UserWithBLOBs extends User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.Password
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.ssl_cipher
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	private String sslCipher;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.x509_issuer
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	private String x509Issuer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.x509_subject
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	private String x509Subject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.plugin
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	private String plugin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.authentication_string
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	private String authenticationString;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.default_role
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	private String defaultRole;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.Password
	 * @return  the value of user.Password
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.Password
	 * @param password  the value for user.Password
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.ssl_cipher
	 * @return  the value of user.ssl_cipher
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	public String getSslCipher() {
		return sslCipher;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.ssl_cipher
	 * @param sslCipher  the value for user.ssl_cipher
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	public void setSslCipher(String sslCipher) {
		this.sslCipher = sslCipher;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.x509_issuer
	 * @return  the value of user.x509_issuer
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	public String getX509Issuer() {
		return x509Issuer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.x509_issuer
	 * @param x509Issuer  the value for user.x509_issuer
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	public void setX509Issuer(String x509Issuer) {
		this.x509Issuer = x509Issuer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.x509_subject
	 * @return  the value of user.x509_subject
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	public String getX509Subject() {
		return x509Subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.x509_subject
	 * @param x509Subject  the value for user.x509_subject
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	public void setX509Subject(String x509Subject) {
		this.x509Subject = x509Subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.plugin
	 * @return  the value of user.plugin
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	public String getPlugin() {
		return plugin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.plugin
	 * @param plugin  the value for user.plugin
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	public void setPlugin(String plugin) {
		this.plugin = plugin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.authentication_string
	 * @return  the value of user.authentication_string
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	public String getAuthenticationString() {
		return authenticationString;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.authentication_string
	 * @param authenticationString  the value for user.authentication_string
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	public void setAuthenticationString(String authenticationString) {
		this.authenticationString = authenticationString;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.default_role
	 * @return  the value of user.default_role
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	public String getDefaultRole() {
		return defaultRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.default_role
	 * @param defaultRole  the value for user.default_role
	 * @mbg.generated  Sat May 13 10:55:18 ICT 2023
	 */
	public void setDefaultRole(String defaultRole) {
		this.defaultRole = defaultRole;
	}
}