package web.nl.kltn.model.generator;

import java.math.BigDecimal;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_id
	 * @mbg.generated  Sat May 13 11:00:18 ICT 2023
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
	 * @mbg.generated  Sat May 13 11:00:18 ICT 2023
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbg.generated  Sat May 13 11:00:18 ICT 2023
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_id
	 * @return  the value of user.user_id
	 * @mbg.generated  Sat May 13 11:00:18 ICT 2023
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_id
	 * @param userId  the value for user.user_id
	 * @mbg.generated  Sat May 13 11:00:18 ICT 2023
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
	 * @return  the value of user.username
	 * @mbg.generated  Sat May 13 11:00:18 ICT 2023
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
	 * @param username  the value for user.username
	 * @mbg.generated  Sat May 13 11:00:18 ICT 2023
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbg.generated  Sat May 13 11:00:18 ICT 2023
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbg.generated  Sat May 13 11:00:18 ICT 2023
	 */
	public void setPassword(String password) {
		this.password = password;
	}
}