package web.nl.kltn.model.generator;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_id
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.fname
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	private String fname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.birthday
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.faculty
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	private String faculty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.student_class
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	private String studentClass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.create_at
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	private Long createAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.update_at
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	private Long updateAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_id
	 * @return  the value of user.user_id
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_id
	 * @param userId  the value for user.user_id
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
	 * @return  the value of user.username
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
	 * @param username  the value for user.username
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.fname
	 * @return  the value of user.fname
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	public String getFname() {
		return fname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.fname
	 * @param fname  the value for user.fname
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	public void setFname(String fname) {
		this.fname = fname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.birthday
	 * @return  the value of user.birthday
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.birthday
	 * @param birthday  the value for user.birthday
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.faculty
	 * @return  the value of user.faculty
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	public String getFaculty() {
		return faculty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.faculty
	 * @param faculty  the value for user.faculty
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	public void setFaculty(String faculty) {
		this.faculty = faculty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.student_class
	 * @return  the value of user.student_class
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	public String getStudentClass() {
		return studentClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.student_class
	 * @param studentClass  the value for user.student_class
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	public void setStudentClass(String studentClass) {
		this.studentClass = studentClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.create_at
	 * @return  the value of user.create_at
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	public Long getCreateAt() {
		return createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.create_at
	 * @param createAt  the value for user.create_at
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	public void setCreateAt(Long createAt) {
		this.createAt = createAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.update_at
	 * @return  the value of user.update_at
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	public Long getUpdateAt() {
		return updateAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.update_at
	 * @param updateAt  the value for user.update_at
	 * @mbg.generated  Mon Jun 05 16:11:48 ICT 2023
	 */
	public void setUpdateAt(Long updateAt) {
		this.updateAt = updateAt;
	}
}